spring.application.name=heroManager
# spring.h2.console.enabled=true
# spring.datasource.url=jdbc:h2:mem:test
spring.jackson.mapper.accept-case-insensitive-enums=true


server.port=8080

logging.level.com.op.heroManager=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect